# Generated by Django 3.0.8 on 2020-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='file_name',
            field=models.CharField(default='face', max_length=256),
        ),
    ]
