# Generated by Django 3.0.8 on 2020-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='User_Name')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full_Name')),
                ('image', models.ImageField(upload_to='Images/')),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TempPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full_Name')),
                ('image', models.ImageField(upload_to='TempImages/')),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
