# Generated by Django 3.0.8 on 2020-12-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='tempperson',
            name='timeStamp',
        ),
    ]
