# Generated by Django 3.0.8 on 2020-12-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('url', models.URLField(primary_key=True, serialize=False, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='asin')),
                ('sid', models.CharField(blank=True, max_length=50, null=True, verbose_name='sid')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('delivery_message', models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery_message')),
                ('item_available', models.BooleanField(blank=True, null=True, verbose_name='item_available')),
                ('main_image', models.URLField(blank=True, null=True, verbose_name='main_image')),
                ('also_bought', models.ManyToManyField(to='recommendation.Product')),
                ('categories', models.ManyToManyField(to='recommendation.Category', verbose_name='categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_bullet', models.CharField(max_length=255, verbose_name='feature_bullet')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True, verbose_name='symbol')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='currency')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='current_price')),
                ('discounted', models.BooleanField(blank=True, null=True, verbose_name='discounted')),
                ('before_price', models.FloatField(blank=True, null=True, verbose_name='before_price')),
                ('savings_amount', models.FloatField(blank=True, null=True, verbose_name='savings_amount')),
                ('savings_percent', models.FloatField(blank=True, null=True, verbose_name='savings_percent')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductReviewMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(blank=True, null=True, verbose_name='total_reviews')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='rating')),
                ('answered_questions', models.IntegerField(blank=True, null=True, verbose_name='answered_questions')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('asin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='asin')),
                ('title', models.CharField(max_length=50, verbose_name='variant')),
                ('image', models.URLField(null=True, verbose_name='image')),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ProductVariant',
                'verbose_name_plural': 'ProductVariants',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('reviewTime', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewerID', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewerName', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewText', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('asin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='feature_bullets',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.ProductFeatureBullet', verbose_name='ProductFeatureBullets'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='recommendation.ProductImage', verbose_name='ProductImages'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.ProductPrice'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.ProductReviewMetaData'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(to='recommendation.ProductVariant'),
        ),
    ]
