# Generated by Django 3.0.8 on 2020-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='category')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, verbose_name='symbol')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('current_price', models.FloatField(verbose_name='current_price')),
                ('discounted', models.BooleanField(verbose_name='discounted')),
                ('before_price', models.FloatField(verbose_name='before_price')),
                ('savings_amount', models.FloatField(verbose_name='savings_amount')),
                ('savings_percent', models.FloatField(verbose_name='savings_percent')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_bullet', models.CharField(max_length=255, verbose_name='feature_bullet')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(verbose_name='total_reviews')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('answered_questions', models.IntegerField(verbose_name='answered_questions')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('asin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='asin')),
                ('variant', models.CharField(max_length=50, verbose_name='variant')),
                ('large_image', models.URLField(verbose_name='large_image')),
            ],
            options={
                'verbose_name': 'ProductVariant',
                'verbose_name_plural': 'ProductVariants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='asin')),
                ('sid', models.CharField(max_length=50, verbose_name='sid')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='description')),
                ('delivery_message', models.CharField(max_length=50, verbose_name='delivery_message')),
                ('item_available', models.BooleanField(verbose_name='item_available')),
                ('main_image', models.URLField(verbose_name='main_image')),
                ('also_bought', models.ManyToManyField(to='recommendation.Product')),
                ('categories', models.ManyToManyField(to='recommendation.Category', verbose_name='categories')),
                ('feature_bullets', models.ManyToManyField(to='recommendation.ProductFeatureBullet', verbose_name='ProductFeatureBullets')),
                ('images', models.ManyToManyField(to='recommendation.ProductImage', verbose_name='ProductImages')),
                ('variants', models.ManyToManyField(to='recommendation.ProductVariant')),
            ],
        ),
    ]
