# Generated by Django 3.0.8 on 2020-12-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ProductPrice',
        ),
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='ProductReviewMetaData',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.ProductPrice'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='recommendation.ProductReviewMetaData'),
        ),
    ]
