# Generated by Django 3.0.8 on 2020-12-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20201218_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='also_bought',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_message',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery_message'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_bullets',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.ProductFeatureBullet', verbose_name='ProductFeatureBullets'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.ProductImage', verbose_name='ProductImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_available',
            field=models.BooleanField(blank=True, null=True, verbose_name='item_available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, null=True, verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.ProductPrice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.ProductReviewMetaData'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='recommendation.ProductVariant'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='before_price',
            field=models.FloatField(blank=True, null=True, verbose_name='before_price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='current_price',
            field=models.FloatField(blank=True, null=True, verbose_name='current_price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='discounted',
            field=models.BooleanField(blank=True, null=True, verbose_name='discounted'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='savings_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='savings_amount'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='savings_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='savings_percent'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='productreviewmetadata',
            name='answered_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='answered_questions'),
        ),
        migrations.AlterField(
            model_name='productreviewmetadata',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='productreviewmetadata',
            name='total_reviews',
            field=models.IntegerField(blank=True, null=True, verbose_name='total_reviews'),
        ),
    ]
