# Generated by Django 3.0.8 on 2020-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20201218_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='also_bought',
            field=models.ManyToManyField(to='recommendation.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='recommendation.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='recommendation.ProductImage', verbose_name='ProductImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='recommendation.ProductReviewMetaData'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(to='recommendation.ProductVariant'),
        ),
    ]
