# Generated by Django 3.0.8 on 2020-12-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20201218_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('reviewTime', models.DateField(blank=True, null=True)),
                ('reviewerName', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewText', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('asin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.Product')),
            ],
        ),
    ]
