# Generated by Django 3.0.8 on 2020-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reviewerID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
